# Generated by Django 5.1.4 on 2024-12-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='arrival_transport',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='departure_transport',
        ),
        migrations.AddField(
            model_name='attendee',
            name='registrar_document',
            field=models.FileField(null=True, upload_to='event_documents/registrar/'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='registrar_document',
            field=models.FileField(null=True, upload_to='event_documents/registrar/'),
        ),
    ]
